### ISSUE TITLE
Bluetooth icon disapeared 

### ISSUE THREAD

**Issue by giovannicaligaris** [elementary/wingpanel-indicator-bluetooth#64]
Juno

Wingpanel-indicator-bluetooth is installed. Everything works fine from switchboard as well. For some reason the icon is missing.

![screenshot from 2018-10-01 18 26 46](https://user-images.githubusercontent.com/26255347/46305006-0c84af80-c5a8-11e8-82a6-4f0317e43d2b.png)

$ rfkill list
0: hci0: Bluetooth
	Soft blocked: no
	Hard blocked: no
1: phy0: Wireless LAN
	Soft blocked: yes
	Hard blocked: no

**Comment by worldofpeace** [comment]
I noticed this also, however it was not consistently gone (after restarting wingpanel it reappeared).
Will observe if it disappears again.

Only change I see to that icon recently was https://github.com/elementary/icons/commit/03df05c821e593deab654deac372546fc5edc5c6

**Comment by danrabbit** [comment]
If you reproduce the issue, can you use Gtk Inspector to see what icon name is being requested by the panel? If it's something that's not in the icon set, then we know the issue is there, but if it's `null` or empty then we know the issue is here in the indicator

**Comment by rasmus91** [comment]
I'm having this same problem, occurred after coming out of suspend.

**Comment by worldofpeace** [comment]
Haven't had time to dig with the gtk inspector but I've been able to reproduce this every time with `systemctl restart bluetooth`.

**Comment by peteruithoven** [comment]
Any change you guys all use the wingpanel-indicator-ayatana ?
Because this issue might be related: https://github.com/elementary/wingpanel/issues/163

**Comment by worldofpeace** [comment]
> Any change you guys all use the wingpanel-indicator-ayatana ?
> Because this issue might be related: [elementary/wingpanel#163](https://github.com/elementary/wingpanel/issues/163)

No, and it is realized when I look in the gtk inspector.

**Comment by ggogobera** [comment]
![screenshot from 2018-10-20 20-54-13](https://user-images.githubusercontent.com/41262747/47258399-a8208600-d4ab-11e8-9d32-7c55a8f5c99f.png)

This is happening in my case... I thought if I turned battery percentage off, it would be fixed but no difference

**Comment by knorquist** [comment]
It disappears after returning from suspend for me. Sometimes the icon is completely gone, and sometimes I can still see a little like @ggogobera.

![screenshot from 2018-10-20 09-57-35](https://user-images.githubusercontent.com/3306524/47527825-67808e00-d858-11e8-8bed-b3726168de11.png)
![screenshot from 2018-10-25 11-54-43](https://user-images.githubusercontent.com/3306524/47527833-6c454200-d858-11e8-9b15-20557a553e00.png)

This is a fresh install so I'm not really sure what's going on.

**Comment by Yansen92** [comment]
Having the same issue. Clicking the blank space still pulls up Bluetooth menu. 

![screenshot from 2018-10-30 13 57 48](https://user-images.githubusercontent.com/17573588/47746551-e7896800-dc4b-11e8-8dae-d42ba59219be.png)

**Comment by peteruithoven** [comment]
If I add and exeption to the following list changing the Reveal transition to anything except SLIDE_LEFT or SLIDE_RIGHT there is no issue.
https://github.com/elementary/wingpanel/blob/master/src/Widgets/Panel.vala#L232-L251

If I switch the transition_type from right to left when making it visible again it also re-appears normally.

**Comment by KadekNusa** [comment]
bluethoot indicator missing
![bluetooth-missing](https://user-images.githubusercontent.com/26836923/50530439-6ad61580-0b38-11e9-82c1-2e53cba63451.png)

**Comment by queeup** [comment]
I think it fixed on master. When are we going to have this fix on our systems?

**Comment by peteruithoven** [comment]
You can see that the fix was merged on jan 14:
https://github.com/elementary/wingpanel/pull/187#event-2072361291
And that the latest release was on may 22: 
https://github.com/elementary/wingpanel-indicator-bluetooth/releases

So you should definitely have the fix by now.

**Comment by queeup** [comment]
Hmmm I have that fix, you are right. But the problem persist on my system. It happens after wake from suspend.

**Comment by peteruithoven** [comment]
@queeup could you open a new issue?
Please include as much info as possible.
For example what happens when you restart the wingpanel (`killall winganel`)?
Is there an empty space where the icon should be? Maybe include a screenshot.
